name: CI - Serverest API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Rodar testes pelo testng.xml
      - name: Run tests with TestNG suite
        run: mvn -B clean test -DsuiteXmlFile=src/test/resources/testng.xml

      # Upload dos relatórios de teste como artefato
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports
